### PR TITLE
Fix external calls failing silently to open magnets

### LINKED ISSUE #304: Copy magnet link to clipboard doesn't work sometimes
Can't reproduce reliably. Started happening after webtorrent was moved to it's own process

### PR DESCRIPTION
**Pull request by leodutra**
XDG based calls (Linux) and direct drags were failing since 3 slashes were being incorrectly inserted in the file URI.

Seems to fix #304.

### CODE REVIEW

**Comment by leodutra** [comment]
@feross This is very small and very useful.

**Comment by leodutra** [comment]
@codealchemist This is pending for a long time and is very important for external tools and xdg activated stuff.

**Comment by leodutra** [comment]
@feross this can be included on v0.19.1

**Comment by feross** [comment]
This PR looks good, but somehow it got weirdly rebased and now there's a ton of extra commits after the relevant changes.

Does someone want to attempt to fix this up so we can merge it?

**Comment by codealchemist** [comment]
Guys, please take a look at #1367.
Thanks!

**Comment by feross** [comment]
Replaced by https://github.com/webtorrent/webtorrent-desktop/pull/1367

**Pull request closed without merging**
