### PR TITLE
Use babel instead of buble

### PR DESCRIPTION
**Pull request by feross**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Inspired by @hicom150's PR https://github.com/webtorrent/webtorrent-desktop/pull/1695, I swapped out `buble` for `babel`.

This way we can target just the JSX transformation. We don't use any other cutting edge JS features that require compilation, nor should we in the future.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by mathiasvr** [comment]
Is this faster than buble?

**Comment by feross** [comment]
1.59s for babel vs 0.82s for buble. I think I'd rather be use `babel` just to be consistent with the majority of the ecosystem, even though it takes a bit longer to build.

**Comment by mathiasvr** [comment]
I’m leaning more towards buble because of speed, but I can see it doesn’t make big difference here.

What exactly becomes more consistent?
I mean is there some obvious drawbacks to using buble?

**Comment by feross** [comment]
I don't feel super strongly, but babel has these advantages:

- Most folks in the React ecosystem use it
- Lets us target just the transformations we want to apply. In this case, we transform only the JSX and don't touch any other part of the code.

**Comment by mathiasvr** [comment]
Applying JSX transformations exclusively sounds great, but in this case I prefer buble simply because it's faster.

I'm fine either way.

**Comment by hicom150** [comment]
Given that `buble` seems to change to `maintenance only` mode https://github.com/bublejs/buble/issues/220 I think that it is the correct time to make the transition to `babel` 😅

**Comment by feross** [comment]
Thanks for the review, @hicom150. I just rebased this and merged it!

**Pull request merged**
