### PR TITLE
Remove forced webtorrent trackers.

### PR DESCRIPTION
**Pull request by KJ2ME**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain: 

**What changes did you make? (Give an overview)**

Remove forced webtorrent trackers.

**Which issue (if any) does this pull request address?**

#1024

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by mathiasvr** [comment]
We need webtorrent trackers for “normal” torrents to make it into the WebRTC peer network.
I think issue #1024 is about creating a torrent file without the trackers.

**Comment by KJ2ME** [comment]
Yes and the client suggest some default trackers when a new torrent is created, but is different if that is forced.

This not remove the suggested trackers, only the forced trackers when the .torrent file is created.

"global.WEBTORRENT_ANNOUNCE" only is used on the creation of the torrent file and generate the #1024 bug.

**Comment by mathiasvr** [comment]
But doesn’t this also remove the trackers for torrents/magnet that are added?

**Comment by KJ2ME** [comment]
No, only remove the create torrent.

I checked where is used before try make the change: https://i.imgur.com/OYC66cT.png

And just in case, just now I tried build and run the app and works fine. This is a magnet link created:

`magnet:?xt=urn:btih:6c2ea2e4d96c039de0e6c319662ccc3e586fd1c3&dn=a95jCIZOQ3s1XXJY.mp4&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com`

It is using the default torrent trackers.

**Comment by mathiasvr** [comment]
Right, I haven’t checked it, but if you add an existing magnet or torrent not created by Webtorrent Desktop, that does not already have the wss trackers, I think they won’t be added automatically after this change. This is important to make this app a “hybrid client”.
The ‘WEBTORRENT_ANNOUNCE‘ global is used by webtorrent (not this app).

**Comment by KJ2ME** [comment]
Why it by intrusive only for be a hybrid client?

For be hybrid only need works with the 2 ways, but only when the user need, not forcing it.

**Comment by mathiasvr** [comment]
Yes, I agree it makes sense to not force it, but because most torrents don't use WebRTC, adding the extra wss trackers by defaults helps bring content to WebRTC peers. It is only hybrid clients that can bridge the two peer networks, and because webtorrent is still relatively new, it makes sense to "force" the wss trackers. In the future, this may not be necessary.

However, it is a problem that the wss trackers are forced into a saved torrent file, even when the user explicitly removed them.

**Comment by KJ2ME** [comment]
Ok, it is understood.

**Comment by subins2000** [comment]
#1836 addresses this

**Pull request closed without merging**
