### PR TITLE
Watch folder

### PR DESCRIPTION
**Pull request by codealchemist**
In response to #1149, this feature adds a preference to watch a folder for new `.torrent` files.
When a torrent file is saved on the watched folder it is automatically added to WebTorrent Desktop.
The feature can be enabled / disabled from preferences.

image

### CODE REVIEW

**Comment by Flet** [comment]
I really like this idea!

I think the wording on the the preferences could be phrased better as its not totally clear to me (and it doesn't mention "watching" at all)

Maybe:
```
(remove the header)

✅ Watch for new .torrent files and add them immediately.
Folder to watch: __________________________________________
```

Also, as this feature feels a little beyond the "keep things simple" user experience of this app, so it may be best to have this turned off by default.

**Comment by codealchemist** [comment]
Hey @Flet, thanks a lot for your feedback!
I like the rewording and simplification.
About the header, I think we still need it because there aren't preferences without headers. If we just remove the header the preference will look like being part of another section.

Maybe we can rename *Downloads* to *Folders* and add it under that section.
@feross, @dcposch, what do you guys think about this change?

Cheers!

**Comment by codealchemist** [comment]
Preview with proposed adjustments:

image

**Comment by codealchemist** [comment]
Hey @Flet, can you provide a review to move this one forward?
Thanks!

**Pull request merged**
