### PR TITLE
macOS: Create Universal application

### PR DESCRIPTION
**Pull request by Teutates**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[ X ] Other, please explain: Adds arm64 arch to macOS build

**What changes did you make? (Give an overview)**

Add arm64 arch to macOS build to create a universal Intel/Apple Silicon app

**Which issue (if any) does this pull request address?**

#1907

**Is there anything you'd like reviewers to focus on?**

N/A

### CODE REVIEW

**Comment by fishcharlie** [comment]
> Is this still relevant?

Yes.

> If so, what is blocking it?

@DiegoRBaquero is assigned and hasn't had any activity on this PR since April 5th. So @DiegoRBaquero is currently blocking this PR.

> Is there anything you can do to help move it forward?

Hopefully tagging @DiegoRBaquero will help move this forward 😉.

---

Really want to see this!

**Comment by DiegoRBaquero** [comment]
Can you please resolve the conflicts?

**Comment by fishcharlie** [comment]
@DiegoRBaquero Not sure I'm gonna be able to do that since I'm not the PR author.

@Teutates can you resolve the merge conflicts?

**Comment by Teutates** [comment]
@fishcharlie @DiegoRBaquero Does this do the trick?

**Comment by treeshateorcs** [comment]
works fine here, i have successfully built webtorrent-desktop for arm64 macos

**Comment by Teutates** [comment]
Bumping @DiegoRBaquero

**Comment by tie** [comment]
If anyone is willing to run code from a random dude on the Internet until this PR gets merged and released, I’ve built the package with `refs/pull/2190/merge` checked out.

https://transfer.sh/xMRjmg/WebTorrent.zip 

@DiegoRBaquero @Teutates is there anything blocking this PR?

**Comment by fishcharlie** [comment]
Yes. It's still relevant. As @Teutates mentioned above: Bumping @DiegoRBaquero

**Comment by ivan-zakharchuk** [comment]
why this wasn't merged since the Autumn?

**Comment by Teutates** [comment]
@DiegoRBaquero latest merge conflicts removed.

**Comment by fishcharlie** [comment]
@DiegoRBaquero this PR has been open for over a year now. Any status updates?

**Comment by tie** [comment]
Yes, this is still relevant. cc @DiegoRBaquero

**Comment by farribeiro** [comment]
I'm considering this project is no longer relevant to webtorrent, need to manually update a lot of dependencies plus webtorrent 2.x doesn't work with this client. apart from electron that is very Old

**Comment by fishcharlie** [comment]
Really disappointing that this was closed. @DiegoRBaquero can we get this reopened and merged?

**Pull request closed without merging**
