### PR TITLE
Update music-metadata dependency

### PR DESCRIPTION
**Pull request by Borewit**
Update from [v2.0.1](https://github.com/Borewit/music-metadata/releases) to [v2.3.2](https://github.com/Borewit/music-metadata/releases).

Release is out for 5 days, no issues reported against it so far.
* [x] Executed smoke-test.
* [x] Update to [v2.4.0](https://github.com/Borewit/music-metadata/releases/tag/v2.3.3)
* [x] Round bit-rate: 812 kbps
* [x] Round sample rate: 44.1 kHz

### CODE REVIEW

**Comment by codealchemist** [comment]
Tested with mp3 and flac, looking good.
:)

image

**Comment by Borewit** [comment]
@codealchemist thanks for reviewing! 
But let's put this merge on hold, look at endless number of digits in the bit-rate in your screenshot.

You probably tested against [v2.3.3](https://github.com/Borewit/music-metadata/releases/tag/v2.3.3) with the bitrate calculation for FLAC included.

I will normalize the bitrate to a rounded number in kb/s.

**Comment by codealchemist** [comment]
Oh, damn! I totally missed that!
Luckily I uploaded the screenshot :)
Thanks!

**Comment by Borewit** [comment]
2018-07-17 bit-rate fixed

It should like that, nothing less ;-)

**Comment by codealchemist** [comment]
When no metadata is available:
image

MP3 with metadata:
image

Metadata looks incomplete though:
image

Not reading metadata for OGG file:
image

Metadata for OGG seems to be present though:
image

BTW, this also happens on current WebTorrent version, so it's not a new thing.
I'm seeing a strange behavior on `playback-controller`.
Looks like metadata can be loaded but we aren't getting it.
I'll keep looking at it.

This is the torrent I used for testing:
https://archive.org/details/wod2015-10-08.radiocity_acidjack

**Comment by codealchemist** [comment]
Hey @Borewit, I created #1440 to show you the changes I introduced.
Are you able to reproduce the issues I was experiencing before that change?

**Comment by codealchemist** [comment]
Implemented on #1440.
Thanks!

**Pull request merged**
