### PR TITLE
Release/v0.19.0

### PR DESCRIPTION
**Pull request by codealchemist**
We already have some nice new features worth sharing with our users on a new release.

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
Only @feross can release

**Comment by codealchemist** [comment]
Hey @feross, shall we do a new release?
Thx!

**Comment by farribeiro** [comment]
Trouble in merging the PR on master branch, I thin because the @ungoldman removed his request. Please force merge

**Comment by feross** [comment]
I'll take a look at this soon. Sorry for the delay folks. I've been away for a while and it's taking me a while to get a handle on everything.

**Comment by codealchemist** [comment]
No problem dude!
Take your time, and thanks for coming back!
:)

**Comment by farribeiro** [comment]
If the merge is successful, is triggered a build of webtorrent-desktop?

**Comment by DiegoRBaquero** [comment]
@farribeiro nope, builds are manual

**Comment by nomenon** [comment]
will there ever be a release?

**Comment by feross** [comment]
Working on releasing this now. Getting the certificates all set up correctly again is a huge nightmare. Still figuring it out.

**Comment by codealchemist** [comment]
Awesome!
🎉

**Comment by farribeiro** [comment]
Boa work for 0.20 tô bump all dependencies

**Pull request merged**
