### PR TITLE
feat: add preference to customize global trackers

### PR DESCRIPTION
**Pull request by subins2000**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Added a new preference item, "Global Trackers". This list will be used as the default announceList instead of `create-torrent` module's list. This is done by setting the global variable `WEBTORRENT_ANNOUNCE`

image

~~Currently it requires a restart for the changes to apply. But I wonder if changes to `WEBTORRENT_ANNOUNCE` will reflect in app runtime after init ? :thinking:~~

Tracker changes will apply on pause & resume of a torrent.

**Which issue (if any) does this pull request address?**

#881

**Is there anything you'd like reviewers to focus on?**

~~Does changes to `WEBTORRENT_ANNOUNCE` reflect in app runtime after init ? :thinking: My guess is that torrent needs to be paused and resumed for the new trackers to get applied ?~~

Changes to `WEBTORRENT_ANNOUNCE` will reflect to future webtorrent `client.add` calls. So pausing and resuming a torrent is enough.

### CODE REVIEW

**Comment by feross** [comment]
Rather than setting `global.WEBTORRENT_ANNOUNCE`, you can just pass in the `announce` option to the `client.add` or `client.seed` methods. That will add the specified trackers to the list of used trackers.

See: https://github.com/webtorrent/webtorrent/blob/2b8f65ab59422a70fe23d529bb9380d71e6cc2d8/lib/torrent.js#L262-L265

**Comment by subins2000** [comment]
In #881, I read

> we're currently adding four default webtorrent (ws:// and wss://) trackers to all torrents without making this very clear to users. There is an argument to be made that we should allow users to turn this off (just from a privacy perspective)`

So change needs to be made to the global variable too, right ? Should I also pass it to `announce` option in `.add` or just applying to the global variable would apply it to there too ?

I'm now trying to avoid loading state in `webtorrent.js` and instead use IPC to pass the global trackers list.

**Comment by subins2000** [comment]
Yes, this is still relevant. Ability to change the default trackers used is important, from a privacy perspective and user experience. Users have submitted duplicate issues since the creation of this PR asking this (#881).

**Comment by DiegoRBaquero** [comment]
@subins2000 is this good to go?

**Review by DiegoRBaquero — APPROVED** [review]

**Pull request merged**
