### PR TITLE
Fix: Increase height of 'About' window

### PR DESCRIPTION
**Pull request by akaustav**
**What is the purpose of this pull request?**

- [x] Bug fix

**What changes did you make?**
Increased the height of the **About WebTorrent** window which shows when you click **Help** > **About WebTorrent**.

**Which issue (if any) does this pull request address?**
#1736

**Is there anything you'd like reviewers to focus on?**
- Tested in Windows 10 (64 bit) only.
- Need help testing in other supported platforms.
- Need instructions/help to update unit tests, and/or end-to-end tests.

**Screenshot**
image

### CODE REVIEW

**Comment by mathiasvr** [comment]
This about window is only used on Windows and Linux, on macOS the native `about` [role](https://electronjs.org/docs/api/menu-item#roles) is used instead, and looks like this:

Screenshot 2019-10-30 at 12 34 30

I see the Copyright notice is missing for the other platforms, it would be great if you could add it as well @akaustav.

**Comment by akaustav** [comment]
Cool, thanks @mathiasvr. I verify that the copyright information is available in the window now. However, `220` height was not sufficient to display the copyright line. So, I had to increase the height even further. After changing the height to `250`, it looks like this in Windows 10:

image

**Comment by akaustav** [comment]
Also, I see that the lines related to Help menu in Windows and Linux:
https://github.com/webtorrent/webtorrent-desktop/blob/0198d7493d1191be7ee8617ef71f2bc12037028e/src/main/menu.js#L441-L450

Also, like @mathiasvr said, here is the code snippet for Mac (Darwin):
https://github.com/webtorrent/webtorrent-desktop/blob/0198d7493d1191be7ee8617ef71f2bc12037028e/src/main/menu.js#L340-L347

However, I fail to understand what controls the height of the about dialog in **macOS**. Does **macOS** automatically adjust the window width and height to accommodate the contents? Or is there a setting in a configuration file somewhere?

Also, would you think it is a good idea to keep the dimensions of the About window/dialog box consistent across multiple platforms?

**Comment by mathiasvr** [comment]
@akaustav On mac the about window is populated with info from the packaging process, and I believe you are correct that the dimensions are automatically adjusted.

I think dimensions should be the same across platforms, but it's more important to have a consistent look.
I tried displaying the Windows/Linux about window on mac and I get this:

Screenshot 2019-10-31 at 17 55 05

It's weird that there is such a big difference between macOS and Windows? However, as long as it looks good in Windows and Linux it's fine since we don't use this window on mac.

**Comment by hicom150** [comment]
This fix looks great, but I found two small issues 😅

- Copyright path should point to `build` instead of `src` otherwise it will not be correctly loaded after packing
- After upgrading `master` electron to `electron@7` there is a small issue to remove the window menu https://github.com/electron/electron/issues/21088 so a I used a small _hack_ 😉

I will add this corrections in the following commit 👍

**Comment by hicom150** [comment]
Good work @akaustav and @mathiasvr 🎉

**Comment by mathiasvr** [comment]
Thanks @hicom150, nice catches 👍

**Pull request merged**
