### PR TITLE
Update to Electron 3

### LINKED ISSUE #1490: Unstable / Crashes with new MacOS Mojave
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.99.3)

**What operating system and version?**
MacOS Mojave (10.14)

**What did you do?**
When adding torrent it crashes, when clicking back to torrent list it also crashes

**What did you expect to happen?**
Not to crash

**What actually happened?**
It Crashed

### PR DESCRIPTION
**Pull request by mathiasvr**
This PR updates electron, electron-packager, and spectron.

I have tried to fix issues related to updating these dependencies, but have only tested it on macOS 10.11.6.

I have fixed and run the integration tests for macOS (the new electron version e.g. renders fonts differently).

It would be great if someone could try this on other platforms, and maybe run/fix the integration tests.

This is a work in progress, current issues:

- [ ]  Wait for electron to fix #1490 
- [x]  Wait for spectron to officially support electron 3
- [ ]  Run integration tests on macOS Mojave
- [ ]  Run/fix integration tests on Windows 10

### CODE REVIEW

**Comment by mathiasvr** [comment]
This PR currently uses a patched version of spectron to support Electron 3.0, but this will probably be fixed soon.

**Comment by mathiasvr** [comment]
@Borewit Thanks for testing and looking into this.

I'm also getting the `Failed to query stereo recording.` message on mac, but it doesn't crash the program.

We should probably wait some time and see if the next electron versions are more stable.

**Comment by Borewit** [comment]
No problem, thank you for pushing the project forward.

**Comment by mathiasvr** [comment]
Note: I tried this on Ubuntu 18.04, seemed to work fine.

**Comment by Borewit** [comment]
Just let me know if I need to reassess.

**Comment by Borewit** [comment]
Umm, @mathiasvr, i'm afraight I overwrote your branch under the assumption it was not longer in use. 

That was pretty stupid action of me.
Even more that it now appears we are redoing your work (still accessible via ["Files Changed"](https://github.com/webtorrent/webtorrent-desktop/pull/1481/files) is still intact). 

Do you mind renaming your branch and push it one more time so I can merge it to [update-electron]?(https://github.com/webtorrent/webtorrent-desktop/tree/update-electron)

Related #1597

**Comment by mathiasvr** [comment]
@Borewit no problem, probably the stale bot's fault 😉 

I can't offer much help at the moment, so it's fine that you redo it if that's easier.
The integration test commits probably aren't relevant anyway.

If you want to try to merge the commits anyway, I think you can run: `git apply https://github.com/webtorrent/webtorrent-desktop/pull/1481.patch` or something like that.

**Pull request closed without merging**
