### PR TITLE
Upgrade to Electron 11

### PR DESCRIPTION
**Pull request by feross**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain: Update dep

**What changes did you make? (Give an overview)**

Upgrade to Electron 11

**Which issue (if any) does this pull request address?**

Possibly addresses #1894

**Is there anything you'd like reviewers to focus on?**

I'd like to start testing out Electron 11 on `master` so we can see if there's any deprecated APIs that we need to upgrade, etc. Then when Electron 11 is stable, we can do another release of the app :)

UPDATE: Electron 11 stable was just released.

### CODE REVIEW

**Comment by feross** [comment]
Electron 11 stable was just released. https://www.electronjs.org/releases/stable#release-notes-for-v1100

No breaking changes.

**Comment by feross** [comment]
Self-merging without review -- sorry. I want to start testing Electron 11 so we're certain it's stable before the next release.

**Comment by hicom150** [comment]
Sorry for the late review 😓

I've noticed that with `electron@11` this error is thrown 
```
electron.remote.screen.getAllDisplays is not a function (telemetry.js:77)
```

I've tested and this error does not appear with `electron@10`, so I suspect that could be something related with the warning that refers to https://github.com/electron/electron/issues/23506

I'm trying to find a fix, but I've not find a solution yet 😓

**Comment by feross** [comment]
I opened an issue to track this error, @hicom150. See #1896

**Pull request merged**
