### PR TITLE
Fix playing back audio files & reading music metadata

### PR DESCRIPTION
**Pull request by Borewit**
Replaced musicmetadata with [music-metadata](https://github.com/Borewit/music-metadata) module. The original one appears to be no longer maintained.

Fixes bug #1320, playing back audio files broken: caused by stream incompatibility between musicmetadata & readable-stream.

Should be faster, more stable is able to read more metadata and format information.
Supports additional audio formats and metadata tag headers.

Added audio format & some release information to the lay screen.

You could also use the library to retrieve album art from the audio files.

### CODE REVIEW

**Comment by Borewit** [comment]
Would be great if one can review this proposal.

**Comment by Borewit** [comment]
Playing [Opus](https://en.wikipedia.org/wiki/Opus_(audio_format)) audio and demonstrating visualization her metadata:
metadata opus

**Comment by Borewit** [comment]
Added separate elements for year & album release information: 

metadata with year release and comments

**Comment by Borewit** [comment]
@codealchemist: can you please review my commits?

**Comment by codealchemist** [comment]
Hi @Borewit !
I really like the improvements on your PR :)
Supporting more audio file types and giving additional metadata looks great!

To test your changes I downloaded a random torrent from Internet Archive:
https://archive.org/details/TvQuran.com__Alafasi

When testing on your PR the info for MP3 files looks way better than before (only shows the filename on latest master):
image

For OGG files now I got a black screen.
On latest master (v0.19) I'm getting some file info:
image

If we can't get metadata maybe we can show the filename instead.

Then, after fully playing an OGG file with your changes I got this error:
```
TypeError: Cannot read property 'title' of undefined
    at renderAudioMetadata (/dev/webtorrent-desktop/build/renderer/pages/player-page.js:209)
```

I can't play this file anymore.
I tested this with the file `01.ogg`.

Please, let me know if you can reproduce the issue.
Thanks!

**Comment by codealchemist** [comment]
Working great with FLAC:
image

Test torrent:
https://archive.org/details/78_the-happy-monster_chubby-jackson-and-his-orchestra-jackson-bauer_gbia0005336b

**Comment by Borewit** [comment]
I appreciate the time you spend on reviewing these changes. Thank you!!

I will check the Ogg, could it be the case that the background meta-data is simply not available?

Can you make the review official, so I am a step closer to have my changes merged into the master branch?

**Comment by codealchemist** [comment]
I added myself as reviewer.
Let me know your findings after investigating that issue with the OGG file.
I'll test any changes you add as soon as possible.

Thanks!

**Comment by Borewit** [comment]
@codealchemist:
> For OGG files now I got a black screen
>      -  After fully playing an OGG file with your changes I got an error
>      -  Let me know if you can reproduce the issue.

I think I have been able to reproduce this issue. To my best understanding it is caused by wrong encoding off the Ogg file, nevertheless I will address it: Borewit/music-metadata#62

**Comment by Borewit** [comment]
Fixed the Ogg metadata (make sure you clear cached metadata by removing and re-adding the torrent):
ogg-al-fatihah

**Comment by Borewit** [comment]
> @codealchemist codealchemist :  If we can't get metadata maybe we can show the filename instead.
That should already be the case:

[  ``const title = common.title ? common.title : fileSummary.name`` ](https://github.com/Borewit/webtorrent-desktop/blob/34463d908405abb828ae6e82ce01f6d411767167/src/renderer/pages/player-page.js#L213)

Recreated a torrent using the same test file, but stripped of all metadata:
ogg-al-fatihah-no-metadata

**Comment by Borewit** [comment]
@DiegoRBaquero: 
> can you include automated tests?

Just to be on the same page, it is not something new I am introducing here. Although did add additional fields in the player page, I believe it fixes and improves existing functionality. As far as I have seen nothing was unit tested yet. Given this context, I think it is a bit odd to _require_ unit test prior to merge, but I do fully understand it is _desired_

The [music-metadata](https://github.com/Borewit/music-metadata) is heavily unit tested, also the ogg file which was causing a problems [has been added](https://github.com/Borewit/music-metadata/commit/0925463547fddc771aefb8c5284c653382c34d34) as a unit test.

But what you are looking for is probably some extension of the `test-integration` demonstrating the metadata resolving is working, right? 

I don't mind to look into it, problem is that I did get it to work so far.
I changed my resolution 1366x768, I see windows popping up, but then it seems to die:
````
C:\Users\Borewit\code\github\webtorrent-desktop>npm run test-integration

> webtorrent-desktop@0.19.0 test-integration C:\Users\Borewit\code\github\webtorrent-desktop
> npm run build && node ./test


> webtorrent-desktop@0.19.0 build C:\Users\Borewit\code\github\webtorrent-desktop
> buble src --output build

TAP version 13
# app runs
ok 1 html title
screenshot diff l2 distance: 1416, rms: 4.499988500819418
ok 2 screenshot comparison app-basic
# torrent-list: show download path missing
C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:313
        throw er
        ^

Error: EBUSY: resource busy or locked, unlink 'C:\Windows\Temp\WebTorrentTest\Temp\WebTorrent Crashes\operation_log.txt'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at rimrafSync (C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:306:17)
    at C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Borewit\code\github\webtorrent-desktop\node_modules\rimraf\rimraf.js:341:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webtorrent-desktop@0.19.0 test-integration: `npm run build && node ./test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webtorrent-desktop@0.19.0 test-integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Borewit\AppData\Roaming\npm-cache\_logs\2018-03-03T14_29_44_838Z-debug.log

C:\Users\Borewit\code\github\webtorrent-desktop>
````

**Comment by Borewit** [comment]
@DiegoRBaquero: I am one step further with the test-integration. At least I can run the `test-audio.js` whicj actually did capture some metadata output testing via screenshot validation. I will update those accordingly.

**Comment by Borewit** [comment]
@DiegoRBaquero : I noticed [βTorrent](https://btorrent.xyz/) can you use a boost as well in audio playback functionality :wink:

**Comment by DiegoRBaquero** [comment]
Works for me now.

@Borewit What would you want to include in BTorrent? The streaming is pretty much restricted to the native browser functionality.

**Comment by Borewit** [comment]
@DiegoRBaquero, in a couple of days I will open an issue on your repo with some ideas.

**Comment by codealchemist** [comment]
Retested with the problematic OGG file and now it works alright :)
image

I think there's still one problem with MP3 files that didn't finish downloading.
Looks like metadata is not yet available and we're displaying a blank screen.
image

**Comment by codealchemist** [comment]
Also, related to unfinished MP3 files: when the file finishes downloading it's not refreshing its metadata, which is available if I go back to the list and play it again.

**Comment by codealchemist** [comment]
An unfinished MP3 file, which shows a blank screen on WebTorrent Desktop, when opened with OSX Preview tool displays metadata:
image

**Comment by codealchemist** [comment]
Just tested reading that incomplete MP3 file with `music-metadata` on a unit test I'm adding and the content looks correct:
```
  Parsing MPEG / ID3v1
    should handle incomplete MP3 file
METADATA: { format:
   { lossless: false,
     dataformat: 'mp3',
     bitrate: 64000,
     sampleRate: 22050,
     numberOfChannels: 2,
     codecProfile: 'CBR',
     numberOfSamples: 95910336,
     duration: 4349.6751020408165,
     tagTypes: [ 'ID3v2.3', 'ID3v1.1' ] },
  native: undefined,
  common:
   { track: { no: null, of: null },
     disk: { no: null, of: null },
     picture: [ [Object] ],
     title: 'Al-An\'am',
     year: 2007,
     comment: [ 'www.TvQuran.com' ],
     album: 'www.TvQuran.com',
     genre: [ 'www.TvQuran.com' ],
     artist: 'Mishary Alafasi - www.TvQuran.com',
     artists: [ 'Mishary Alafasi - www.TvQuran.com' ] } }
```

**Comment by codealchemist** [comment]
@Borewit, BTW, this is really cool:
image

Nice integration and great coverage ;)

**Comment by DiegoRBaquero** [comment]
This is looking really promising.

**Comment by Borewit** [comment]
@feross: Can you please merge this one?

**Comment by Borewit** [comment]
Fantastic news, finally merged yeah!!

Thank you so much @codealchemist.

**Comment by DiegoRBaquero** [comment]
@feross we need a new release

**Comment by codealchemist** [comment]
I think we should wait until #1361 gets reviewed and merged before a new release.
:)

Thanks @DiegoRBaquero !

**Comment by feross** [comment]
Will wait until #1361 is merged before doing a new release. Does someone want to take a stab at PR'ing the changelog for the next version?

**Comment by codealchemist** [comment]
I'll take the stab at it.
:)

**Pull request merged**
