### PR TITLE
Update music-metadata to version 4.2

### PR DESCRIPTION
**Pull request by Borewit**
- Update music-metadata to version [~~4.1.1~~](https://github.com/Borewit/music-metadata/releases/tag/v4.1.1) [4.2.0](https://github.com/Borewit/music-metadata/releases/tag/v4.2.0)
- Adapt to it's API changes: `format.dataformat` replaced by `format.container` & `format.codec`

### CODE REVIEW

**Comment by Borewit** [comment]
If you have time Alberto, you know the drill ;-)

**Comment by feross** [comment]
Okay, let's land this.

**Comment by codealchemist** [comment]
Sorry guys, lots of stuff going on over here.
Thanks for moving this forward!
:)

**Comment by feross** [comment]
<3

**Pull request merged**
