### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by codealchemist**
I'd love some feedback on this one.
If we want to support plugins this might be a good start.
I already have the first working plugin too:
https://github.com/codealchemist/webtorrent-transparent

You can test it by adding it to WebTorrent Desktop config like this:
```
  "plugins": {
    "webtorrent-transparent": "codealchemist/webtorrent-transparent"
  }
```

Hope we can make progress in this direction :)
Cheers!

### CODE REVIEW

**Comment by talarari** [comment]
what's the status on this? is plugin support being worked on?

**Comment by codealchemist** [comment]
@talarari I provided something like an MVP / working prototype on the plugins system based on Zeit's Hyper.
This includes our first plugin, useful to test the plugins system.
I was waiting for feedback about this and some help to polish it.

Thanks for your interest!

**Comment by codealchemist** [comment]
@DiegoRBaquero maybe we can close this one too.
It's been a long time since anyone pushed for plugins and if we ever decide we want it it might be better to start from scratch.
Cheers!

**Comment by DiegoRBaquero** [comment]
> @DiegoRBaquero maybe we can close this one too.
> It's been a long time since anyone pushed for plugins and if we ever decide we want it it might be better to start from scratch.
> Cheers!

understood, thank you!

**Pull request closed without merging**
