### PR TITLE
Electron 27 update + fix

### PR DESCRIPTION
**Pull request by bendlas**
[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Event format seems to have changed, so don't use `event.sender`, but `main.win` in `main/windows/main.js`

**Which issue (if any) does this pull request address?**

Supersedes https://github.com/webtorrent/webtorrent-desktop/pull/2385

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by bendlas** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

Very much so, I would even say it's security-relevant. I'm happy to resolve the merge, if it has any chance of being reviewed.

I'm also happy to become a member and help with maintenance, if that's an option for you @feross.

Also cc @ThaUnknown, @DiegoRBaquero, since you still seem to be active in this org.

**Comment by bendlas** [comment]
btw, in NixOS, we're delivering this right now, in order to keep pace as we deprecate old electron versions: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/webtorrent_desktop/default.nix#L12-L23

**Comment by farribeiro** [comment]
> > Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> Very much so, I would even say it's security-relevant. I'm happy to resolve the merge, if it has any chance of being reviewed.
> 
> I'm also happy to become a member and help with maintenance, if that's an option for you @feross.
> 
> Also cc @ThaUnknown, @DiegoRBaquero, since you still seem to be active in this org.

It would be interesting for you to contact the @feross asking to join the organization

**Comment by bendlas** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

The only thing blocking this is lack of response from maintainers!

cc @feross @alxhotel @bnjmnt4n @Borewit @DiegoRBaquero @Flet @gillesdemey @imsnif @iovis @ivantodorovich @josephfrazier @mappum @mvayngrib @rom1504 @SilentBot1 @ThaUnknown @transitive-bullshit @watson 

PS as stated previously, I'm willing to step up and take maintainership

**Comment by ThaUnknown** [comment]
pinging 18 people? do you have a death wish?

**Comment by gillesdemey** [comment]
Took this for a quick spin on MacOS and the app doesn't appear to be interactive – seems the main culprit is applying `-webkit-app-region: drag;` on the entire application instead of just the header.

```css
.app {
  -webkit-app-region: drag;
}
```

should be 

```css
.header {
  -webkit-app-region: drag;
}
```

Can you also rebase with `master`?

**Comment by farribeiro** [comment]
> > Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> The only thing blocking this is lack of response from maintainers!
> 
> cc @feross @alxhotel @bnjmnt4n @Borewit @DiegoRBaquero @Flet @gillesdemey @imsnif @iovis @ivantodorovich @josephfrazier @mappum @mvayngrib @rom1504 @SilentBot1 @ThaUnknown @transitive-bullshit @watson
> 
> PS as stated previously, I'm willing to step up and take maintainership

try on Discord

**Comment by ThaUnknown** [comment]
yet another 18 pings, how wonderful

**Comment by bendlas** [comment]
> try on Discord

In fact I have done that a few weeks back https://discord.com/channels/612575111718895616/841760353439973376/1189956775680671854

> pinging 18 people? do you have a death wish?

What's that supposed to mean? I know you didn't just issue a credible threat to my life in a public forum, so I can only assume that this is some sort of hyperbole?

**Comment by rom1504** [comment]
@bendlas does it work? Comments above seem to indicate it doesn't

**Comment by bendlas** [comment]
@rom1504  It has been working on linux and it has been what we're shipping on linux, due to older versions of electron being disabled for security reasons.

**Comment by farribeiro** [comment]
Don't forget to update WebTorrent to version 2.x

**Comment by bendlas** [comment]
> Don't forget to update WebTorrent to version 2.x

Are you sure that should be done as part of this PR?

**Comment by gillesdemey** [comment]
> @gillesdemey thanks for the constructive feedback! Would you mind re-testing? I don't have access to a MacOS machine 

Issue is resolved; I think we're good to merge this :)

> Don't forget to update WebTorrent to version 2.x

I'd rather see a separate PR to upgrade the webtorrent dependency since that's a major version bump (and it could block this PR). 

It could include some patches for dependencies – @bendlas if you're concerned about those I encourage you to send a PR for that too ;)

**Review by gillesdemey — APPROVED** [review]
LGTM :shipit:

**Comment by farribeiro** [comment]
yeah... finally

**Pull request merged**
