### PR TITLE
Removed zero-fill

### PR DESCRIPTION
**Pull request by jimmywarting**
sets the version the same way webtorrent dose it

https://github.com/webtorrent/webtorrent/blob/f8923a66a8b1178a412b067bc913e267025b3d57/index.js#L27-L29

### CODE REVIEW

**Comment by dsernst** [comment]
Can you explain the motivation ? :)

**Comment by jimmywarting** [comment]
Have none other then "doing it the same way webtorrent" 

And also possible removing zero-fill completely in the second last place 

https://github.com/webtorrent/webtorrent-desktop/blob/81e6d7f3a756862de89861b7f152727ebb0ed0cb/src/renderer/pages/player-page.js#L741-L744

...by replacing it with native [padStart](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) to reduce the dependencies

**Comment by feross** [comment]
@jimmywarting Can you send another PR to completely remove `zero-fill`, as you mentioned in your comment? Thanks!

**Comment by jimmywarting** [comment]
> Can you send another PR to completely remove zero-fill, as you mentioned in your comment? Thanks!

sure, will do it soon

**Pull request merged**
