### PR TITLE
fix: use the flatpack version of VLC

### PR DESCRIPTION
**Pull request by Acelya-9028**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I split the string returned by the `vlc-command` package to separate the command from its arguments.

https://github.com/feross/vlc-command/blob/master/index.js#L64

**Which issue (if any) does this pull request address?**

The flatpack version of VLC does not work because the `vlc-command` package return `flatpak run org.videolan.VLC` and this is interpreted as the whole command instead of the command with its arguments.

https://github.com/webtorrent/webtorrent-desktop/issues/2094

Not exactly the same but this [trick](https://github.com/flathub/io.webtorrent.WebTorrent/issues/3) is not needed in this case now.

`echo -e '#!/bin/sh\n\nflatpak run org.videolan.VLC $@' > ~/spawn-vlc.sh`

### CODE REVIEW

**Review by nuzzesick — APPROVED** [review]

**Comment by Acelya-9028** [comment]
Yes still relevant

**Comment by Acelya-9028** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

YES!

**Comment by Acelya-9028** [comment]
YES!

**Comment by r14c** [comment]
the bot keeps marking this issue as stale, but it would nice to have a fix.

https://github.com/webtorrent/webtorrent-desktop/issues/2101

**Comment by Acelya-9028** [comment]
This project is dead af sorry :(

**Comment by Acelya-9028** [comment]
> Why on earth is this not merged ? The issue is still here in 2025 !

This shitty tool is dead as fuck…

**Pull request closed without merging**
