### PR TITLE
Improve the poster selection for audio/music based torrent

### PR DESCRIPTION
**Pull request by Borewit**
Addressing issue #1332

### CODE REVIEW

**Comment by Borewit** [comment]
@codealchemist: Alberto, can you please review this one as well?

**Comment by codealchemist** [comment]
I'm getting this error:
image

I was able to reproduce with MP3 files only so far.
Good thing is this should get fixed by #1361 :)

**Comment by codealchemist** [comment]
Latest merge on this branch fixed thee issues I saw before, yay!

Properly displaying poster before all metadata was downloaded:
image

Properly displaying poster after metadata was downloaded:
image

Content list background:
image

Torrent list poster looking good:
image

**Comment by codealchemist** [comment]
I was wondering if we should also display the same background on the torrent details view (files list).
Anyway, this looks really good!
Nice enhancement @Borewit!

**Comment by codealchemist** [comment]
Hey @feross, if you agree I think we should merge this one too and then I'll prepare the changelog on another PR.

**Comment by Borewit** [comment]
That was probably not a good idea to commit on top of this pull request after the merge.
I created a new push request: #1368,

**Pull request merged**
