### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by codealchemist**
Bumping up minor version.

### CODE REVIEW

**Comment by codealchemist** [comment]
Hey @Flet, here's an easy review.
I'm just bumping up the minor version to include this new feature on the next release.

BTW, @DiegoRBaquero, what are the steps to make a new release?
Thx!

**Comment by ungoldman** [comment]
@codealchemist please read the [Release Procedure](https://github.com/webtorrent/webtorrent-desktop/blob/master/CONTRIBUTING.md#release-procedure) section of the contributing guidelines. All steps are documented there. If you have any trouble with one of the steps, please let us know. Thanks for working on this!

**Comment by DiegoRBaquero** [comment]
@codealchemist Right now only @feross can do releases as he has the dev accounts & signing certs.

He recently renewed the cert iirc. If it's ok with @feross I can accept whatever is needed to make a release and help you guys with it.

**Comment by codealchemist** [comment]
@ungoldman Already did a rebase on my PR branch and pushed.
Please, let me know if it's ok, or how to check it.
I'm not used to work with rebase.
Thx!

**Comment by ungoldman** [comment]
Closing this PR as it looks like changes got in elsewhere.

**Comment by codealchemist** [comment]
Thanks @ungoldman :)

**Pull request closed without merging**
