### PR TITLE
Store magnet URI once torrent has been parsed

### LINKED ISSUE #1035: TypeError: Error processing argument at index 0, conversion failure from undefined
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** Mac, Windows

From our telemetry error logs, we picked up this error. It occurred 27 times today.

```
Processes: main window, platforms: darwin win32, versions: 0.15.0 0.16.0 0.17.1 0.17.2
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at click (.../build/renderer/controllers/torrent-list-controller.js:217:54)
    at CallbacksRegistry.apply (/Applications/WebTorrent.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/electron.asar/renderer/api/remote.js:282:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### PR DESCRIPTION
**Pull request by Goldob**
Fixes #1035.

### CODE REVIEW

**Comment by Goldob** [comment]
To see why this will work, refer to `lib/torrent.js` implementation in [webtorrent](https://github.com/feross/webtorrent) package. In particular, see that before the `infoHash` event is [emitted](https://github.com/feross/webtorrent/blob/be0d9a2562a2c9b03952308c91cb8dbf69163ee1/lib/torrent.js#L266), `_processParsedTorrent()` function is [called](https://github.com/feross/webtorrent/blob/be0d9a2562a2c9b03952308c91cb8dbf69163ee1/lib/torrent.js#L247), which in turn [sets](https://github.com/feross/webtorrent/blob/be0d9a2562a2c9b03952308c91cb8dbf69163ee1/lib/torrent.js#L299) `torrent.magnetURI` field.

I realize this is a hacky solution, but right now webtorrent doesn't provide any kind of more appropriate event to know when torrent has been parsed. I guess it's worth to look into this as well.

**Comment by mathiasvr** [comment]
Looks good, I think we should reopen/merge considering that this fixes a bug.

**Comment by feross** [comment]
@mathiasvr I can't re-open this PR as the original repo has been deleted.

**Comment by mathiasvr** [comment]
Okay, I opened a new PR with this commit as I seem to remember it as a good fix, but must admit that I lost a bit of context over time.

**Comment by feross** [comment]
Cool, thanks @mathiasvr. Merged!

**Pull request closed without merging**
